Lunch/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import YearView, MonthView

urlpatterns = [
    path('', MonthView.as_view(), name="index"),

    path('months_by_year/', YearView.as_view(), name="calendar"),
    path('months_by_year/<int:year>', YearView.as_view(), name="calendarWithYear"),
    path('months_by_year/save/<int:year>/<int:month>', YearView.as_view(), name="setBalance"),

    path('days_by_month/<int:year>/<int:month>', MonthView.as_view(), name="month"),
    path('days_by_month/save/<int:year>/<int:month>/<int:day>', MonthView.as_view(), name="monthSave"),
    path('days_by_month/validate/<int:year>/<int:month>/<int:day>', MonthView.as_view(), name="validate_saldo"),

    path('', include('user.urls')),

    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('admin/', admin.site.urls),
]

user/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('validate/login/', LoginView.as_view(), name="validateLogin"),

    path('password_reset/', PasswordResetView.as_view(), name="password_reset"),
    path('password_reset/done/', PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('reset/done/', PasswordResetCompleteView.as_view(), name="password_reset_complete"),


]

app/models.py
from django.db import models
import calendar, datetime
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Sum, F, FloatField

# Create your models here.


class Day(models.Model):
    realDate = models.DateField(auto_now=True, null=True, blank=True)
    DAYS = [(i+1,i+1) for i in range(31)]
    day = models.IntegerField(
        choices=DAYS,
        default=1,
    )
    month = models.ForeignKey("Month", on_delete=models.CASCADE)
    spent = models.FloatField(default=0.0)
    def __str__(self):
        return str(self.day)

    @property
    def year(self):
        return self.month.year
    @property
    def weekday(self):
        try:
            weekday = calendar.weekday(self.year.year, self.month.month, self.day)
            if weekday == 0:
                return "Mon"
            elif weekday == 1:
                return "Tue"
            elif weekday == 2:
                return "Wed"
            elif weekday == 3:
                return "Thu"
            elif weekday == 4:
                return "Fri"
            elif weekday == 5:
                return "Sat"
            elif weekday == 6:
                return "Sun"
            else:
                return ""
        except ValueError:
            return ""

    @property
    def weekdayNumber(self):
        try:
            return calendar.weekday(self.year.year, self.month.month, self.day)
        except ValueError:
            return ""

    @property
    def getDayCssClass(self):
        year = datetime.datetime.now().year
        month = datetime.datetime.now().month
        day = datetime.datetime.now().day
        if self.day == day and self.month.month == month and self.month.year.year == year:
            return "btn-outline-info"
        elif self.spent:
            return "btn-outline-danger"
        else:
            return "btn-primary"




class Month(models.Model):
    month = models.IntegerField()
    balance = models.FloatField(default=0.0)
    year = models.ForeignKey("Year", null=False, blank=False, on_delete=models.CASCADE)

    def __str__(self):
        if self.month == 1:
            return "January"
        if self.month == 2:
            return "February"
        if self.month == 3:
            return "March"
        if self.month == 4:
            return "April"
        if self.month == 5:
            return "May"
        if self.month == 6:
            return "June"
        if self.month == 7:
            return "July"
        if self.month == 8:
            return "August"
        if self.month == 9:
            return "September"
        if self.month == 10:
            return "October"
        if self.month == 11:
            return "November"
        if self.month == 12:
            return "December"

    def mini(self):
        if self.month == 1:
            return "Jan"
        if self.month == 2:
            return "Feb"
        if self.month == 3:
            return "Mar"
        if self.month == 4:
            return "Apr"
        if self.month == 5:
            return "May"
        if self.month == 6:
            return "Jun"
        if self.month == 7:
            return "Jul"
        if self.month == 8:
            return "Aug"
        if self.month == 9:
            return "Sep"
        if self.month == 10:
            return "Oct"
        if self.month == 11:
            return "Nov"
        if self.month == 12:
            return "Dec"

    def total_month(self):
        tot = self.day_set.all().aggregate(
            tot_ped=Sum(F('spent'), output_field=FloatField())
        )['tot_ped'] or 0.0
        return round(tot,2)
    total_month.short_description = "Total Spent"

    totalLunch = property(total_month)

    def balaceDep(self):
        bMonthSpent = self.year.month_set.filter(month__lte=self.month, year__year=self.year.year).aggregate(
            bMonth=Sum(F('day__spent'), output_field=FloatField())
        )['bMonth'] or 0.0

        bMonthsBalance = self.year.month_set.filter(month__lte=self.month, year__year=self.year.year).aggregate(
            bMonths=Sum(F('balance'), output_field=FloatField())
        )['bMonths'] or 0.0

        return round(bMonthsBalance - bMonthSpent,2)

class Year(models.Model):
    year = models.IntegerField()

    def __str__(self):
        return str(self.year)

    def total_year(self):
        tot = self.month_set.all().aggregate(
            tot_ped=Sum(F("day__spent"), output_field=FloatField())
        )['tot_ped'] or 0.0
        return round(tot,2)

    total_year.short_description = "Total Spent"
    totalLunch = property(total_year)



@receiver(post_save, sender=Month)
def set_all_days_in_month(sender, instance:Month, **kwargs):
    monthObj = Month.objects.get(month=instance.month, year__year=instance.year.year)

    if monthObj.day_set.count() != 0:
        return

    r = calendar.monthrange(instance.year.year, instance.month)[1]
    days = (Day(day=i + 1, month=instance) for i in range(r))

    instance.day_set.bulk_create(days)

@receiver(post_save, sender=Year)
def set_all_months_in_year(sender, instance:Year, **kwargs):

    yearObj = Year.objects.get(year=instance.year)

    if yearObj.month_set.count() != 0:
        return

    list = (Month(month=i+1, year=instance) for i in range(12))
    instance.month_set.bulk_create(list)
    list = instance.month_set.all()
    for m in list:
        r = calendar.monthrange(m.year.year, m.month)[1]
        days = (Day(day=i+1, month=m) for i in range(r))
        m.day_set.bulk_create(days)

app/templates/app/calendar.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block title %} Calendar {% endblock %}

{% block main %}
<div class="container-fluid">
    <div class="row ">
        <div id="calendar" class="col-12 col-sm-12 col-md-8 col-lg-8 col-xl-9" style="transition-duration: .5s">
            <nav class="nav nav-tabs " id="YearTab" role="tablist">
                {% for y in object_list %}
                    {% if y.year == activeYear %}
                        <a class="nav-item nav-link active" id="nav-{{ y }}-tab" data-toggle="pill" href="#nav-{{ y }}" role="tab" aria-controls="vnav-{{ y }}" aria-selected="true">{{ y }}</a>
                    {% else %}
                        <a class="nav-item nav-link" id="nav-{{ y }}-tab" data-toggle="pill" href="#nav-{{ y }}" role="tab" aria-controls="nav-{{ y }}" aria-selected="false">{{ y }}</a>
                    {% endif %}
                {% endfor %}
            </nav>
            <div class="tab-content" id="v-pills-tabContent">
                {% for y in object_list %}
                    {% if y.year == activeYear %}
                        <div class="tab-pane fade show active " id="nav-{{ y }}" role="tabpanel" aria-labelledby="nav-{{ y }}-tab">
                            <div class="row">
                                {% for m in y.month_set.all %}
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3" style="margin-bottom: 20px">
                                        {% if currentMonth == m.month and y.year == currentYear %}
                                          <div class="card text-center border-white bg-primary">
                                            <div class="card-header border-white text-white">
                                        {% else %}
                                          <div class="card text-center">
                                            <div class="card-header border-primary">
                                        {% endif %}
                                                <h5 class="">{{ m }}</h5>
                                            </div>
                                            <div class="card-body">
                                                <button  type="button"  class="btn btn-success" data-toggle="modal" data-target="#modal{{ y }}{{ m.month }}">
                                                    Balance:<br> R$ {{ m.balaceDep|intcomma }}
                                                </button>
                                                {% if currentMonth == m.month and y.year == currentYear %}
                                                    <a href="{% url "month" y.year m.month %}" class="btn btn-outline-light">Total Spent:<br> R$ {{ m.total_month|intcomma }}</a>
                                                {% else %}
                                                    <a href="{% url "month" y.year m.month %}" class="btn btn-primary">Total Spent:<br> R$ {{ m.total_month|intcomma }}</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                      </div>
                                {% endfor %}
                            </div>
                        </div>
                     {% else %}
                        <div class="tab-pane fade " id="nav-{{ y }}" role="tabpanel" aria-labelledby="nav-{{ y }}-tab">
                            <div class="row">
                                {% for m in y.month_set.all %}
                                    <div class="col-12 col-sm-12 col-md-6 col-lg-4 col-xl-3" style="margin-bottom: 20px">
                                        {% if currentMonth == m.month and y.year == currentYear %}
                                          <div class="card text-center border-white bg-primary">
                                            <div class="card-header border-white text-white">
                                        {% else %}
                                          <div class="card text-center">
                                            <div class="card-header border-primary">
                                        {% endif %}
                                                <h5 class="">{{ m }}</h5>
                                            </div>
                                            <div class="card-body">
                                                <button  type="button"  class="btn btn-success" data-toggle="modal" data-target="#modal{{ y }}{{ m.month }}">
                                                    Balance:<br> R$ {{ m.balaceDep|intcomma }}
                                                </button>
                                                {% if currentMonth == m.month and y.year == currentYear %}
                                                    <a href="{% url "month" y.year m.month %}" class="btn btn-outline-light">Total Spent:<br> R$ {{ m.total_month|intcomma }}</a>
                                                {% else %}
                                                    <a href="{% url "month" y.year m.month %}" class="btn btn-primary">Total Spent:<br> R$ {{ m.total_month|intcomma }}</a>
                                                {% endif %}
                                            </div>
                                        </div>
                                      </div>
                                {% endfor %}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            {% for y in object_list %}
                {% for m in y.month_set.all %}
                     <!-- Modal -->
                    <div class="modal fade" id="modal{{ y }}{{ m.month }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h2 class="modal-title text-center" id="">{{ m }} {{ y }} </h2><br>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                            <form action="{% url 'setBalance' y.year m.month %}" method="POST">
                                <div class="modal-body">
                                  {% csrf_token %}
                                  <div class="form-group">
                                      <label for="#id_balance{{ y }}{{ m.month }}">Balance setted: R$ {{ m.balance }}</label>
                                      <input type="number" name="balance" autofocus class="form-control form-control-lg" id="id_balance{{ y }}{{ m.month }}" onchange="" required />
                                  </div>
                                  <div class="form-group" id="errors{{ y }}{{ m.month }}">
        {#                            {% for e in errors.spent %}#}
        {#                                <div class="alert alert-primary" role="alert">#}
        {#                                  {{ e }}#}
        {#                                </div>#}
        {#                            {% endfor %}#}
                                  </div>

                                </div>
                                  <div class="modal-footer">
                                    <button type="submit" class="btn btn-success">Save</button>
                                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                                  </div>
                            </form>
                        </div>
                      </div>
                    </div>
                {% endfor %}
            {% endfor %}
        </div>
        <div id="actions" class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3" style="transition-duration: .0s; margin-top: 38px">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="align-self-end position-absolute">
                            <button id="arrow-icon-button" class="btn btn-outline-info" onclick="minimizeActions()">
                                <i id="arrow-icon" class="fas fa-chevron-down" style="transition-duration: 0.7s"></i>
                            </button>
                        </div>
                        <div class="card-header text-center">
                            <h5 class="text-info"> Actions </h5>
                        </div>
                        <button class="btn btn-success" data-toggle="modal" data-target="#balanceModal">
                            Add balance to all months
                        </button>
                        <button class="btn btn-info" data-toggle="modal" data-target="#balanceModal">
                            Update balance to all months
                        </button>
                        <button class="btn btn-danger" data-toggle="modal" data-target="#balanceModal">
                            Remove balance of all months
                        </button>
                    </div>
                </div>
                {% if user.is_staff %}
                <div class="col-12 mt-2">
                    <div class="card">
                        <div class="card-header text-center">
                            <h5 class="text-info"> Admin </h5>
                        </div>
                        <button class="btn btn-success" data-toggle="modal" data-target="#balanceModal">
                            Add new year
                        </button>
                    </div>
                </div>
                {% endif %}
            </div>
            <!-- Modal -->
            <div class="modal fade" id="balanceModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h2 class="modal-title text-center" id="">Add balance to all months</h2><br>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                    <form action="" method="POST">
                        <div class="modal-body">
                          {% csrf_token %}
                          <div class="form-group">
                              <label for="#id_balance">Balance setted: R$ </label>
                              <input type="number" name="balance" autofocus class="form-control form-control-lg" id="id_balance" onchange="" required />
                          </div>
                          <div class="form-group" id="errors">
    {#                            {% for e in errors.spent %}#}
    {#                                <div class="alert alert-primary" role="alert">#}
    {#                                  {{ e }}#}
    {#                                </div>#}
    {#                            {% endfor %}#}
                          </div>

                        </div>
                          <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Save</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                          </div>
                    </form>
                </div>
              </div>
            </div>
        </div>

    </div>
</div>
<div class="container">


</div>

{% endblock %}

{% block footer %}
      <div class="container-fluid">

      </div>
{% endblock %}
{% block js %}
    <script src="{% static 'app/js/year.js' %}"></script>
{% endblock js %}

app/templates/app/days.html
{% load humanize %}
<div class="mb-5">
    <div class="btn-group mr-2 w-100" role="group" aria-label="First group">
        {% for siglaWeek in weekSiglas %}
            <button type="button" class="btn btn-success w-100" style="padding: 8px 10px" disabled>{{ siglaWeek }}</button>
        {% endfor %}
    </div>
    {% for week in weeksOnMonth %}
        <div class="row">
            <div class="col-12">
                    <div class="btn-group mr-2 w-100" role="group" aria-label="First group">
                        {% for d in week %}
                            {% if d != 0 %}
                                <button type="button" class="btn {{ d.getDayCssClass }}  w-100" style="padding: 8px 10px" data-toggle="modal" data-target="#modal{{ m }}{{ d.day }}" >{{ d.day }}</button>
                            {% else %}
                                <button type="button" class="btn btn-primary w-100" style="padding: 8px 10px" disabled></button>
                            {% endif %}
                        {% endfor %}
                    </div>
            </div>
        </div>
    {% endfor %}
</div>

app/templates/app/daysInMonth.html
{% load humanize %}



{% for d in weekDisplayInMonth %}
            <div class="col-6 col-sm-6 col-md-4 col-lg-2 col-lx-1" style="margin-bottom: 20px">
                {% if currentDay == d.day and m.month == currentMonth and m.year.year == currentYear %}
                    <div class="card border-info text-center text-white bg-secondary">
                {% else %}
                    <div class="card text-center text-white bg-secondary">
                {% endif %}
                    <div class="card-header">
                        <h5 class="">{{ d.weekday }} {{ d.day|ordinal }}</h5>
                    </div>
                    <div class="card-body">
                        {% if d.weekdayNumber == 5 or d.weekdayNumber == 6  %}
                            <button disabled type="button"  class="btn btn-primary" data-toggle="modal" data-target="#modal{{ m }}{{ d.day }}">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        {% else %}
                            <button  type="button"  class="btn btn-primary" data-toggle="modal" data-target="#modal{{ m }}{{ d.day }}">
                                R$: {{ d.spent|intcomma }}
                            </button>
                        {% endif %}
                    </div>
                </div>
            </div>
{% endfor %}

app/templates/app/month.html
{% extends 'base.html' %}
{% load appTags %}
{% load humanize %}
{% load static %}


{% block title %} Calendar {% endblock %}

{% block main %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-xs-12 ">
            <h2 class="pt-3"><a href="{% url 'calendarWithYear' activeYear %}">{{ activeYear }}</a></h2>
        </div>
    </div>
    <nav class="nav nav-tabs justify-content-end" id="YearTab" role="tablist">
    <div class="dropdown">
        {% for m in object_list %}
            {% if m.month == activeMonth %}
                <button class="btn btn-outline-light dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ m.mini }}
                </button>
            {% endif %}
        {% endfor %}
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu">
            <h6 class="dropdown-header">Months</h6>
            <div class="dropdown-divider"></div>
            {% for m in object_list %}
                {% if m.month == activeMonth %}
                    <a class="dropdown-item active" id="dropdown-item{{ m.month }}" onclick="selectMonth({{ m.month }}, '{{ m.mini }}')" data-toggle="tab" href="#nav-{{ m.month }}" role="tab" aria-controls="nav-{{ m.month }}" aria-selected="true">{{ m }}</a>
                {% else %}
                    <a class="dropdown-item" id="dropdown-item{{ m.month }}" onclick="selectMonth({{ m.month }}, '{{ m.mini }}')" data-toggle="tab" href="#nav-{{ m.month }}" role="tab" aria-controls="nav-{{ m.month }}" aria-selected="false">{{ m }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
    </nav>
    <div class="tab-content">
        {% for m in object_list %}
            {% if m.month == activeMonth %}
                <div class="tab-pane fade show active" id="nav-{{ m.month }}" role="tabpanel" aria-labelledby="dropdown-item{{ m.month }}" style="transition-duration: 0.5s">

{#                        {% for d in m.day_set.all %}#}
{#                            {% display_calendar m activeYear %}#}
                            {% display_days m activeYear %}
{#                        {% endfor %}#}

                </div>
             {% else %}
                <div class="tab-pane fade" id="nav-{{ m.month }}" role="tabpanel" aria-labelledby="dropdown-item{{ m.month }}" style="transition-duration: 0.5s">

{#                        {% display_calendar m activeYear %}#}
                        {% display_days m activeYear %}

                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% for m in object_list %}
        {% for d in m.day_set.all %}
            <!-- Modal -->
            <div class="modal fade" id="modal{{ m }}{{ d.day }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content text-white bg-primary">
                  <div class="modal-header">
                    <h2 class="modal-title text-center" id="">{{ d.weekday }} {{ m }} {{ d.day|ordinal }} </h2><br>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                    <form action="{% url "monthSave" m.year.year m.month d.day %}" method="POST">
                        <div class="modal-body">
                          {% csrf_token %}
                          <div class="form-group">
                              <label for="#id_spent{{ m.month }}{{ d }}">Spent</label>
                              <input type="text" name="spent" placeholder="{{ d.spent }}" autofocus class="form-control form-control-lg" id="id_spent{{ m.month }}{{ d }}" onchange="validate({{ d }}, {{ m.month }}, {{ activeYear }})" required />
                          </div>
                          <div class="form-group" id="errors{{ m.month }}{{ d }}">
                            {% for e in errors.spent %}
                                <div class="alert alert-daanger" role="alert">
                                  {{ e }}
                                </div>
                            {% endfor %}
                          </div>

                        </div>
                          <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Save</button>
                            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                          </div>
                    </form>
                </div>
              </div>
            </div>

        {% endfor %}
    {% endfor %}
    <div class="modal fade bd-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-sm">
        <div class="modal-content">
          ...
        </div>
      </div>
    </div>

</div>

{% endblock %}

{% block footer %}
      <div class="container">

      </div>
{% endblock %}
{% block js %}
    <script src="{% static 'app/js/month.js' %}"></script>
{% endblock js %}